# https://github.com/wolfi-dev/os/blob/efdcceb832ece89b3ab84e9b2ee089fd9d758715/mysql-9.5.yaml
package:
  name: mysql-8.0
  version: "8.0.44"
  epoch: 0
  description: "The MySQL open source relational database"
  copyright:
    - license: GPL-2.0-only
  resources:
    cpu: 30
    memory: 60Gi
  dependencies:
    runtime:
      - ${{package.name}}-client
      - merged-usrsbin
      - pwgen
      - wolfi-baselayout
    provides:
      - mysql=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - doxygen
      - graphviz
      - libaio-dev
      - libevent-dev
      - libtirpc-dev
      - linux-pam-dev
      - ncurses-dev
      - openssl-dev
      - pcre2-dev
      - pkgconf
      - readline-dev
      - rpcsvc-proto
      - systemd-dev
      - wolfi-baselayout
      - xz-dev
      - zlib-dev
  environment:
    DATADIR: /var/lib/mysql
    SOCKDIR: /run/mysqld

pipeline:
  - working-directory: /home/build/mysql
    pipeline:
      - uses: fetch
        with:
          uri: https://dev.mysql.com/get/Downloads/${{package.name}}/mysql-${{package.version}}.tar.gz
          expected-sha256: 609522ed1fefce5ab388dec25e0d1bce132382da26e2b77b68f0741c0a641356
      - uses: cmake/configure
        with:
          opts: |
            -DWITH_UNIT_TESTS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DSYSCONFDIR=/etc \
            -DMYSQL_DATADIR=$DATADIR \
            -DMYSQL_UNIX_ADDR=$SOCKDIR/mysqld.sock \
            -DDEFAULT_CHARSET=utf8mb4 \
            -DDEFAULT_COLLATION=utf8mb4_general_ci \
            -DENABLED_LOCAL_INFILE=ON \
            -DINSTALL_INFODIR=share/info \
            -DINSTALL_MANDIR=share/man \
            -DINSTALL_PLUGINDIR=lib/${{package.name}}/plugin \
            -DINSTALL_INCLUDEDIR=include/mysql \
            -DINSTALL_DOCREADMEDIR=share/doc/${{package.name}} \
            -DINSTALL_SUPPORTFILESDIR=share/support/${{package.name}} \
            -DINSTALL_MYSQLSHAREDIR=share/${{package.name}} \
            -DINSTALL_DOCDIR=share/doc/${{package.name}} \
            -DSYSTEMD_SERVICES_DIR=lib/systemd/system \
            -DSYSTEMD_TMPFILES_DIR=lib/tmpfiles.d \
            -DWITH_ASAN=OFF \
            -DWITH_JEMALLOC=OFF \
            -DWITH_LIBWRAP=OFF \
            -DWITH_SYSTEMD=ON \
            -DWITH_SSL=system \
            -DWITH_VALGRIND=OFF \
            -DWITH_ZLIB=system
      - uses: cmake/build
        with:
          opts: |
            -- -j2
      - uses: cmake/install
      # CMAKE_INSTALL_PREFIX=/usr confuses this.
      - name: "Fix installation path of systemd components"
        runs: |
          mv "${{targets.destdir}}"/usr/usr/lib/* "${{targets.destdir}}"/usr/lib/
          rmdir -p --ignore-fail-on-non-empty "${{targets.destdir}}"/usr/usr/lib
      - name: "Remove extras"
        runs: |
          rm -r "${{targets.destdir}}"/usr/mysql-test/
      - name: "Create runtime directories"
        runs: |
          mkdir -p "${{targets.destdir}}"$DATADIR "${{targets.destdir}}"$SOCKDIR

  - uses: strip

subpackages:
  - name: "${{package.name}}-dev"
    description: "headers for mysql"
    dependencies:
      provides:
        - mysql-dev=${{package.full-version}}
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf

  - name: "${{package.name}}-client"
    dependencies:
      provides:
        - mysql-client=${{package.full-version}}
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/mysql "${{targets.subpkgdir}}"/usr/bin/
    test:
      pipeline:
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: mysql-client
            real-pkg-name: ${{subpkg.name}}

  - name: "${{package.name}}-oci-entrypoint"
    description: Entrypoint for MySQL in OCI containers
    dependencies:
      runtime:
        - bash
        - busybox
        - merged-usrsbin
        - openssl
        - wolfi-baselayout
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cp docker-entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
          chmod +x ${{targets.subpkgdir}}/usr/bin/docker-entrypoint.sh
    test:
      pipeline:
        - runs: |
            test /usr/bin/docker-entrypoint.sh

  - name: "${{package.name}}-oci-entrypoint-compat"
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf /usr/bin/docker-entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
          ln -sf /usr/bin/docker-entrypoint.sh ${{targets.subpkgdir}}/usr/local/bin/docker-entrypoint.sh
    dependencies:
      runtime:
        - "${{package.name}}-oci-entrypoint"
        - merged-usrsbin
        - wolfi-baselayout
    test:
      pipeline:
        - runs: |
            test /entrypoint.sh
            test /usr/local/bin/docker-entrypoint.sh

  - name: "${{package.name}}-systemd-units"
    description: "systemd units for MySQL"
    dependencies:
      runtime:
        - mysql=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/systemd/system
          mv "${{targets.destdir}}"/usr/lib/systemd/system/* "${{targets.subpkgdir}}"/usr/lib/systemd/system
          rmdir -p --ignore-fail-on-non-empty "${{targets.destdir}}"/usr/lib/systemd/system

update:
  enabled: true
  github:
    identifier: mysql/mysql-server
    strip-prefix: mysql-
    use-tag: true
    tag-filter: mysql-8.0.

test:
  environment:
    contents:
      packages:
        - ${{package.name}}
        - ${{package.name}}-client
        - ${{package.name}}-dev
        - gcc
        - make
        - glibc-dev
  pipeline:
    - uses: test/tw/ldd-check
      with:
        extra-library-paths: "/usr/lib/private"
    - name: Check versions
      runs: |
        mysql --version |grep "${{package.version}}"
        mysqladmin --version | grep "${{package.version}}"
    - name: Test
      uses: test/daemon-check-output
      with:
        setup: |
          mkdir -p /var/tmp /var/log/mysql /run/mysqld
          mysqld --initialize-insecure
        start: mysqld --user=root
        post: |
          mysqladmin --user=root ping --wait=5
          mkdir -p /tmp/mysql-test
          cat << 'EOF' > test.c
          #include <mysql/mysql.h>
          #include <stdio.h>
          #include <stdlib.h>

          int main() {
              MYSQL *conn;
              conn = mysql_init(NULL);

              if (conn == NULL) {
                  fprintf(stderr, "mysql_init() failed\n");
                  return EXIT_FAILURE;
              }

              if (mysql_real_connect(conn, "127.0.0.1", "root", "", NULL, 3306, NULL, 0) == NULL) {
                  fprintf(stderr, "mysql_real_connect() failed: %s\n", mysql_error(conn));
                  mysql_close(conn);
                  return EXIT_FAILURE;
              }

              printf("Connected to MySQL server successfully.\n");
              mysql_close(conn);
              return EXIT_SUCCESS;
          }
          EOF
          gcc -o test test.c -lmysqlclient
          ldd ./test | grep libmysqlclient # Verify correct library linkage
          ./test | grep "Connected to MySQL server successfully."
        timeout: 60
        expected_output: |
          starting as process
          ready for connections
