# https://cwrap.org/nss_wrapper.html
# https://raw.githubusercontent.com/wolfi-dev/os/4d42d7f64c24b5013f702d5d5a6820e357e5d6d2/nss_wrapper.yaml
package:
  name: nss_wrapper
  version: 1.1.16
  epoch: 1
  description: "A wrapper for the user, group and hosts NSS API"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - ca-certificates-bundle
      - cmake
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.samba.org/nss_wrapper.git
      tag: "${{ package.name }}-${{ package.version }}"
      expected-commit: 2270a7cda76de28c554a7ed1167e49ce19a0fc2f

  # nss_wrapper requires an out of tree build
  # https://git.samba.org/?p=nss_wrapper.git;a=blob;f=README.install;h=7ee4e714ab69c85591dacee8e115d93d764d29a4;hb=2270a7cda76de28c554a7ed1167e49ce19a0fc2f
  - working-directory: output
    pipeline:
      - runs: |
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=MinSizeRel ..
      - uses: autoconf/make
      - uses: autoconf/make-install
      - runs: |
          # Remove uneeded Perl wrapper (nss_wrapper.pl)
          rm -rf ${{ targets.destdir }}/usr/bin

      - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: Development files for ${{package.name}}
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/ldd-check
          with:
            packages: nss_wrapper-dev
    dependencies:
      runtime:
        - ${{package.name}}
        - merged-sbin
        - wolfi-baselayout

  - name: ${{package.name}}-doc
    description: Manpages for ${{package.name}}
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
    dependencies:
      runtime:
        - merged-sbin
        - wolfi-baselayout

update:
  enabled: true
  git:
    strip-prefix: nss_wrapper-
  schedule:
    period: monthly

test:
  environment:
    contents:
      packages:
        - posix-libc-utils
  pipeline:
    - uses: test/pkgconf
    - uses: test/ldd-check
      with:
        packages: ${{package.name}}
    - runs: |
        echo "testuser:x:1001:1000:Test User:/home/testuser:/bin/false" > /tmp/passwd
        echo "root:x:65534:65532:Fake root User:/home/root:/bin/false" >> /tmp/passwd
        echo "users:x:1000:" > /tmp/group
        echo "root:x:65532:" >> /tmp/group
    - runs: |
        LD_PRELOAD=libnss_wrapper.so \
        NSS_WRAPPER_PASSWD=/tmp/passwd \
        NSS_WRAPPER_GROUP=/tmp/group \
        getent passwd testuser
